### ISSUE TITLE
weird type error crash

### ISSUE THREAD

**Issue by nathan7** [feross/standard#104]
```
buffer.js:84
    throw new TypeError('must start with number, buffer, array or string');
          ^
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:84:11)
    at new Buffer (buffer.js:52:3)
    at /home/nathan/src/github.com/then/promise/node_modules/standard/node_modules/string-to-stream/index.js:19:17
    at process._tickCallback (node.js:361:13)
```

**Comment by nathan7** [comment]
specifically, this is due to `StringStream(undefined)` being called

**Comment by nathan7** [comment]
welp, seems I just need to upgrade

**Comment by feross** [comment]
Nice - glad you figured it out! :+1:
