### ISSUE TITLE
Absolute path to symbolic link crashes the app (at least on OSX)

### ISSUE THREAD

**Issue by leomelin** [feross/standard#114]
Noticed that newer version than 3.3.0 (problem doesn't occur there) crash (at least on OSX) if standard is pointing to a file with absolute path, e.g. let's say
````
standard /var/www/fooBar/foo.js
````

The crash message:
````
standard: Unexpected linter output:

Error: ENOENT, no such file or directory '/private/var/www/fooBar/var/www/fooBar/foo.js'
    at Error (native)
    at Object.fs.statSync (fs.js:721:18)
    at walk (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/util/traverse.js:36:15)
    at /usr/local/lib/node_modules/standard/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/util/traverse.js:101:11)
    at CLIEngine.executeOnFiles (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/cli-engine.js:284:9)
    at /usr/local/lib/node_modules/standard/index.js:111:52
    at zalgoSafe (/usr/local/lib/node_modules/standard/node_modules/dezalgo/dezalgo.js:20:10)
    at done (/usr/local/lib/node_modules/standard/node_modules/run-parallel/index.js:18:15)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard
````
It seems to duplicate the path when /var -directory is a symbolic link, like it usually is on OSX pointing to /private/var

**Comment by feross** [comment]
Thanks for reporting. Looks like we just needed to do a `path.resolve` instead of `path.join`
here: https://github.com/feross/standard/commit/3bbb5aa220960f51ac248281a60b99
ac43df8ab1

Released as 3.6.1.
