### ISSUE TITLE
Error with esprima.js

### ISSUE THREAD

**Issue by Sheraff** [feross/standard#150]
Some error I'm getting when simply running `standard-format` in a folder.

```
/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:5283
            throw e;
                  ^
Error: Line 10: Unexpected token else
    at createError (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2306:21)
    at unexpectedTokenError (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2381:13)
    at throwUnexpectedToken (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2386:15)
    at consumeSemicolon (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2501:13)
    at parseReturnStatement (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4175:17)
    at parseStatement (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4408:24)
    at parseIfStatement (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3907:22)
    at parseStatement (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4406:24)
    at parseStatementListItem (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3716:16)
    at parseFunctionSourceElements (/usr/local/lib/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4498:23)
```

**Comment by feross** [comment]
Can you file this on the standard-format repo? https://github.com/maxogden/standard-format

Also, please share the contents of the file that it's failing in, since that's probably relevant.
