### ISSUE TITLE
Breaks with latest babel-eslint

### ISSUE THREAD

**Issue by ligthyear** [feross/standard#348]
Running `standard` using the latest version of babel-eslint fails with an internal error:

```
 ./node_modules/standard/bin/cmd.js **/**.jsx
standard: Unexpected linter output:

TypeError: Cannot read property 'loc' of undefined
    at EventEmitter.validateSpacingBeforeParentheses (/Users/ben/dev/beavy/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/rules/space-before-function-paren.js:92:29)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/ben/dev/beavy/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/Users/ben/dev/beavy/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/Users/ben/dev/beavy/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/eslint.js:771:36)
    at Controller.__execute (/Users/ben/dev/beavy/node_modules/standard/node_modules/standard-engine/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/ben/dev/beavy/node_modules/standard/node_modules/standard-engine/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/Users/ben/dev/beavy/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/eslint.js:768:24)
    at processText (/Users/ben/dev/beavy/node_modules/standard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:225:27)
```

Versions used: 
 - babel-eslint: 5.0.0-beta4
 - standard: 5.4.1

**Comment by SEAPUNK** [comment]
+1, would be awesome if standard started working again.

**Comment by hzoo** [comment]
Published babel-eslint@5.0.0-beta6 which hopefully fixes getters/setters.

**Comment by SEAPUNK** [comment]
@hzoo Looks like it's working pretty well now; thanks!

**Comment by Flet** [comment]
Cool, so can this be closed @SEAPUNK?

**Comment by SEAPUNK** [comment]
@Flet With my code, sure. I don't know if it will still work w/ @ligthyear's code, though.

Personally, I'd close this issue, since this is still primarily a `babel-eslint` problem.

**Comment by Flet** [comment]
Closing. @ligthyear feel free to add a comment if this doesn't make sense.

**Comment by ligthyear** [comment]
Not sure this is actual babel-eslint's problem. [We solved it by using babel-eslint with the `standard`-profile instead](https://github.com/beavyHQ/beavy/issues/45). So I can neither confirm nor deny that this still broken at the moment.
