### ISSUE TITLE
Error: Failed to load plugin

### ISSUE THREAD

**Issue by thessem** [feross/standard#458]
Hi, I'm getting the following error when trying to run standard

```
tandard: Unexpected linter output:

Error: Failed to load plugin react-native: Cannot find module 'eslint-plugin-react-native'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.module.exports.load (/Users/prximac03/.nvm/versions/node/v5.5.0/lib/node_modules/standard/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Users/prximac03/.nvm/versions/node/v5.5.0/lib/node_modules/standard/node_modules/eslint/lib/config/plugins.js:134:21)
    at Config.getConfig (/Users/prximac03/.nvm/versions/node/v5.5.0/lib/node_modules/standard/node_modules/eslint/lib/config.js:256:17)
    at processText (/Users/prximac03/.nvm/versions/node/v5.5.0/lib/node_modules/standard/node_modules/eslint/lib/cli-engine.js:155:27)
    at processFile (/Users/prximac03/.nvm/versions/node/v5.5.0/lib/node_modules/standard/node_modules/eslint/lib/cli-engine.js:227:18)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
```

I have the following in my packages.json
```
{
  <snip>
  "devDependencies": {
    "eslint": "^2.4.0",
    "babel-eslint": "^5.0.0",
    "eslint-plugin-react": "^4.2.1",
    "eslint-plugin-react-native": "^1.0.0",
    "eslint-plugin-flowtype": "^2.1.2",
    "standard": "^3.13.2",
    "standard-format": "^2.1.1"
  },
  "standard": {
    "parser": "babel-eslint",
    "plugins": [
      "react",
      "react-native",
      "flowtype"
    ]
  }
}
```
and I am running Node v5.5.0 and NPM 3.8.1. This is after a fresh install after completely removing my node_modules directory.

The relevant node_modules installed are
```
% npm list | grep eslint
├─┬ babel-eslint@5.0.0
├─┬ eslint@2.4.0
├── eslint-plugin-flowtype@2.1.2
├── eslint-plugin-react@4.2.1
├── eslint-plugin-react-native@1.0.0
│ ├─┬ UNMET PEER DEPENDENCY eslint@0.21.2
│ ├── eslint-config-standard@1.3.1
│ ├── UNMET PEER DEPENDENCY eslint-plugin-react@2.7.1
npm ERR! peer dep missing: eslint@0.x, required by eslint-config-standard@1.3.1
npm ERR! peer dep missing: eslint-plugin-react@^2.1.0, required by eslint-config-standard@1.3.1
```

**Comment by feross** [comment]
You have warnings in the output of `npm list`. You should fix those.

Your using a really new version of `eslint` and `eslint-plugin-react` and that's conflicting with the really old version of `standard` you're using.
