### ISSUE TITLE
"Unexpected linter output" error

### ISSUE THREAD

**Issue by dcposch** [feross/standard#465]
Error message:
```
> webtorrent-app@0.0.0 test /home/dc/webtorrent-app
> standard

standard: Unexpected linter output:

TypeError: Cannot read property 'type' of undefined
    at isRedundantSuperCall (/home/dc/webtorrent-app/node_modules/standard/node_modules/eslint/lib/rules/no-useless-constructor.js:24:38)
    at EventEmitter.checkForConstructor (/home/dc/webtorrent-app/node_modules/standard/node_modules/eslint/lib/rules/no-useless-constructor.js:52:46)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/dc/webtorrent-app/node_modules/standard/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/home/dc/webtorrent-app/node_modules/standard/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/home/dc/webtorrent-app/node_modules/standard/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/home/dc/webtorrent-app/node_modules/standard/node_modules/eslint/lib/eslint.js:839:36)
    at Controller.__execute (/home/dc/webtorrent-app/node_modules/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/dc/webtorrent-app/node_modules/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
npm ERR! Test failed.  See above for more details.
```

To reproduce, run `npm test` (or equivalently, `standard`) on the following code: https://github.com/feross/webtorrent-app/pull/195/commits/f71343dc80ae70b94a348bae6edf4cc36f3e7b42

**Comment by dcposch** [comment]
**Update:** looks like this happened because I used the ES6 `class` keyword.

`standard` should either support those new ES6 features, or give a more descriptive error message

**Comment by feross** [comment]
@dcposch The code that you linked to has since disappeared. Can you paste an example here? The `class` keyword should work without crashing eslint, I believe. So, there's probably a bug in eslint somewhere. If you paste your code, I can look at it and file any needed issues / send a pr to eslint.

**Comment by dcposch** [comment]
Found it:

```js
class UnplayableError extends Error {
  constructor () {
    this.message = 'Can\'t play any files in torrent'
  }
}
```

**Comment by dcposch** [comment]
K here's a minimal way to reproduce it.

**Works:** (`standard` outputs linter errors, but doesn't crash)

```js
class MyClass extends Error {
  constructor () {
  }
}
```

**Works:**

```js
class MyClass {
  constructor () {
    this.n = 0
  }
}
```

**Crashes:**

```js
class MyClass extends Error {
  constructor () {
    this.n = 0
  }
}
```

**Comment by feross** [comment]
This is an esint bug: https://github.com/eslint/eslint/issues/5662

**Comment by feross** [comment]
Looks like this is fixed on eslint `master`. Once the version after 2.4.0 is released, we can bump it in `standard`.

**Comment by feross** [comment]
Bumped eslint to 2.8.0 -- closing this now.
