### ISSUE TITLE
Errors in esformatter when using --format

### ISSUE THREAD

**Issue by megastef** [feross/standard#50]
```
standard --format
/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:4118
            throw e;
                  ^
Error: Line 1439: Unexpected token else
    at createError (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2030:21)
    at unexpectedTokenError (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2099:13)
    at throwUnexpectedToken (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2104:15)
    at consumeSemicolon (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:2216:13)
    at parseStatement (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3628:9)
    at parseIfStatement (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3114:22)
    at parseStatement (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3591:24)
    at parseIfStatement (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3118:25)
    at parseStatement (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3591:24)
    at parseSourceElement (/usr/local/lib/node_modules/standard/node_modules/standard-format/node_modules/esformatter/node_modules/rocambole/node_modules/esprima/esprima.js:3881:24)
```

**Comment by feross** [comment]
This is an issue for the `standard-format` module to fix. Can you open an issue on https://github.com/maxogden/standard-format ?
