### ISSUE TITLE
--stdin causing a TypeError to be thrown with Node v6

### ISSUE THREAD

**Issue by jrmull** [feross/standard#504]
I first noticed this after my linting stopped working in SublimeText using SublimeLinter after installing Node v6. It seems to be related to this change https://github.com/nodejs/node/pull/5348

The error can be seen in the Sublime console (with SublimeLinter in debug mode) or at the shell by:

```
$ cat test.js | standard.cmd --stdin --verbose
standard: Unexpected linter output:

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:887:5)
    at processText (C:\Users\user\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine.js:144:30)
    at CLIEngine.executeOnText (C:\Users\user\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine.js:671:26)
    at Linter.lintText (C:\Users\user\AppData\Roaming\npm\node_modules\standard\node_modules\standard-engine\index.js:66:59)
    at C:\Users\user\AppData\Roaming\npm\node_modules\standard\node_modules\standard-engine\bin\cmd.js:112:16
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by purepear** [comment]
Same here

**Comment by tjaartvdwalt** [comment]
same for me

**Comment by feross** [comment]
This looks like an old eslint that is not present in newer version. The reason that standard 6.0.7 works is that it refers to the eslint version with `^`. But we pinned eslint using `~` in 6.0.8.

This isn't an issue in standard 7.0.0 anymore since eslint is upgraded. Give standard v7 a try!

**Comment by tjaartvdwalt** [comment]
great! thank for fixing it.
