### ISSUE TITLE
Running npm test in TravisCI

### ISSUE THREAD

**Issue by kuronaru** [feross/standard#643]
I've been using `standard` for awhile and it's my first time encountering this.
I always run `npm test` before pushing code to GitHub and have TravisCI integration and it's my first time seeing this error:

```
> standard
standard: Unexpected linter output:
Error: standard:
    Configuration for rule "no-constant-condition" is invalid:
    Value "2,[object Object]" has more items than allowed.
Referenced from: /home/travis/build/kuronaru/qazi/node_modules/standard/eslintrc.json
    at validateRuleOptions (/home/travis/build/kuronaru/qazi/node_modules/eslint/lib/config/config-validator.js:102:15)
    at /home/travis/build/kuronaru/qazi/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (/home/travis/build/kuronaru/qazi/node_modules/eslint/lib/config/config-validator.js:147:35)
    at load (/home/travis/build/kuronaru/qazi/node_modules/eslint/lib/config/config-file.js:390:19)
    at /home/travis/build/kuronaru/qazi/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/home/travis/build/kuronaru/qazi/node_modules/eslint/lib/config/config-file.js:309:28)
    at Object.load (/home/travis/build/kuronaru/qazi/node_modules/eslint/lib/config/config-file.js:395:22)
    at loadConfig (/home/travis/build/kuronaru/qazi/node_modules/eslint/lib/config.js:74:33)
If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

**Comment by feross** [comment]
In addition to `standard`, are you depending on an old version of `eslint`? `standard` requires eslint 3.x.

If you can't figure it out, please paste the output of `npm ls --depth=50` here.

**Comment by nueko** [comment]
Confirmed.
also tried with the latest eslint.
[issue.standar.txt](https://github.com/feross/standard/files/582371/issue.standar.txt)

**Comment by feross** [comment]
Try removing `gulp-eslint` which is depending on an old version of `eslint`.
