### ISSUE TITLE
Don't try to access files that should be ignored.

### ISSUE THREAD

**Issue by purpleKarrot** [feross/standard#680]
I have some files that cannot be accessed by the current user. Even though I have listed them in both ".gitignore" and "standard.ignore", I get the following output:

```
> standard --verbose | snazzy

standard: Unexpected linter output:

Error: EACCES: permission denied, scandir '...'
```

**Comment by feross** [comment]
This happens with raw eslint, so it's not something that `standard` is doing. See:

```
$ ls -lha t.js
-rw-------  1 root  wheel    19B Jan 12 21:57 t.js
$ ./node_modules/.bin/eslint -c eslintrc.json .
EACCES: permission denied, open '/Users/feross/code/standard-stuff/standard/t.js'
Error: EACCES: permission denied, open '/Users/feross/code/standard-stuff/standard/t.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at processFile (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/cli-engine.js:302:21)
    at executeOnFile (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/cli-engine.js:672:25)
    at fileList.forEach.fileInfo (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/cli-engine.js:710:13)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/cli-engine.js:709:18)
    at Object.execute (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/cli.js:171:107)
    at Object.<anonymous> (/Users/feross/code/standard-stuff/standard/node_modules/eslint/bin/eslint.js:74:28)
```

I suggest fixing the permission issue with the file, or if you feel strongly, open an issue on the ESLint bug tracker here: https://github.com/eslint/eslint/issues
