### ISSUE TITLE
Erring with 'Unexpected linter output'

### ISSUE THREAD

**Issue by matthewadams** [feross/standard#833]
Similar to https://github.com/feross/standard/issues/465, but different.
```
$ node --version
v6.10.1
$ npm --version
3.10.10
$ npm i --save-dev standard@9.0.2
# ...
$ standard
standard: Unexpected linter output:

RangeError: Line number out of range (line 1005 requested, but only 1004 lines present).
    at SourceCode.getIndexFromLoc (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/util/source-code.js:389:19)
    at Object.fix (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
    at RuleContext.report (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/rule-context.js:127:34)
    at Program:exit.allLines.reduce.concat.reduce (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
    at Array.reduce (native)
    at EventEmitter.Program:exit (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/util/node-event-generator.js:294:22)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
ADA6011@pumba:~/dev/ms-accounts (next-gen *+)
$ standard --verbose
standard: Unexpected linter output:

RangeError: Line number out of range (line 1005 requested, but only 1004 lines present).
    at SourceCode.getIndexFromLoc (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/util/source-code.js:389:19)
    at Object.fix (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
    at RuleContext.report (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/rule-context.js:127:34)
    at Program:exit.allLines.reduce.concat.reduce (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
    at Array.reduce (native)
    at EventEmitter.Program:exit (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/ADA6011/dev/ms-accounts/node_modules/eslint/lib/util/node-event-generator.js:294:22)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
```
Trying to figure out which of my files is causing it so I can add reproducible test case...will update issue when I find it.

**Comment by matthewadams** [comment]
Found the problem. When the last line has a single blank space, eslint bombs out:
```
class Foo {
}
// next line has a single blank space
 
 ```
_Note the last line above as a single blank space in it!_

Removing the line with the single blank space allows `standard` & `eslint` to work properly.

**Comment by feross** [comment]
Thanks for the bug report, @matthewadams. It looks like this is a recently reported issue in ESLint. See here: https://github.com/eslint/eslint/issues/8401 There's already a PR out, just waiting to get merged and released.

> It appears that this error is consistently thrown if the file ends in a new line with a space character. When I delete the space, the error goes away.

It's not ideal, but at least it looks like it's possible to workaround this crash until ESLint releases a fix.

**Comment by matthewadams** [comment]
FYI, https://github.com/eslint/eslint/issues/8403

**Comment by matthewadams** [comment]
Ok, just saw your comment while I was entering the `eslint` issue. I'll go mark mine as a duplicate. #fastresponse

**Comment by feross** [comment]
@matthewadams Haha, thanks for taking the time to file an issue with ESLint, even though it wasn't necessary in this case :) Very nice of you!

**Comment by feross** [comment]
I think this issue can be closed, since it's not something that we can fix in `standard`. We'll just wait for the ESLint fix.

**Comment by matthewadams** [comment]
Sure sounds good!  :)
